name: ReplenishResources
main: aieuo\ReplenishResources
version: 1.0
api: [3.0.0]
load: POSTWORLD
author: aieuo
commands:
 reso:
  description: 好きなブロックでワールド作成
  usage: /reso <pos1 | pos2 | add | del | setting>
  permission: op